# Generated by Django 3.1.2 on 2020-10-06 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('date_invoice', models.DateField(auto_now_add=True)),
                ('dni', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('address_type', models.CharField(choices=[('calle', 'calle'), ('camino', 'camino'), ('avenida', 'avenida')], default='calle', max_length=7)),
                ('location', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibill_api.product')),
            ],
        ),
    ]
