# Generated by Django 3.1.2 on 2020-10-06 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sibill_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='location',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='province',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='surname',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='iva',
            field=models.DecimalField(decimal_places=2, default='21', max_digits=5),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=9)),
                ('address', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('address_type', models.CharField(choices=[('cl', 'calle'), ('cm', 'camino'), ('av', 'avenida')], default='cl', max_length=7)),
                ('location', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('invoices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sibill_api.invoice')),
            ],
        ),
    ]
