# Generated by Django 3.1.2 on 2020-10-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sibill_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_invoice',
            field=models.DateField(auto_now_add=True),
        ),
    ]
